# Generated by Django 3.1.5 on 2021-01-15 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateur', '0003_delegate_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delegate',
            name='date',
        ),
    ]
